/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MmsbSelect {
    'boldOnSelected': boolean;
    'color'?: string;
    'data': [string, string][];
    'getSelected': () => Promise<string | string[]>;
    'height': string;
    'is_open': boolean;
    'label': string;
    'multiple': boolean;
    'onSelect'?: (select: string) => void;
    'onUnselect'?: (select: string) => void;
    'selected': string[];
  }
}

declare global {


  interface HTMLMmsbSelectElement extends Components.MmsbSelect, HTMLStencilElement {}
  var HTMLMmsbSelectElement: {
    prototype: HTMLMmsbSelectElement;
    new (): HTMLMmsbSelectElement;
  };
  interface HTMLElementTagNameMap {
    'mmsb-select': HTMLMmsbSelectElement;
  }
}

declare namespace LocalJSX {
  interface MmsbSelect {
    'boldOnSelected'?: boolean;
    'color'?: string;
    'data'?: [string, string][];
    'height'?: string;
    'is_open'?: boolean;
    'label'?: string;
    'multiple'?: boolean;
    'onMmsb-select.select'?: (event: CustomEvent<string>) => void;
    'onMmsb-select.unselect'?: (event: CustomEvent<string>) => void;
    'onSelect'?: (select: string) => void;
    'onUnselect'?: (select: string) => void;
    'selected'?: string[];
  }

  interface IntrinsicElements {
    'mmsb-select': MmsbSelect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mmsb-select': LocalJSX.MmsbSelect & JSXBase.HTMLAttributes<HTMLMmsbSelectElement>;
    }
  }
}


